version: "3.8"

services:
  mongodb:
    container_name: alli_mongodb
    image: mongo:6.0.2
    ports:
      - ${DB_EXTERNAL_PORT}:27017
    env_file:
      - ./backend/.env
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  backend:
    container_name: alli_backend
    image: alli_backend:${ENV_NAME}
    build:
      context: backend
      args:
        ENV_NAME: ${ENV_NAME}
    ports:
      - ${BACKEND_EXTERNAL_PORT}:8000
    env_file:
      - ./backend/.env
    command: ${BACKEND_CMD}
    volumes:
      - ./backend/:/app/
    depends_on:
      - mongodb

  frontend:
    container_name: alli_frontend
    image: node:16-alpine
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:3000
    command: npm run dev
    volumes:
      - ./frontend/:/app/
    working_dir: /app/

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
