version: "3.8"

services:
  alli_db:
    container_name: alli_db
    image: mongo:6.0.2
    ports:
      - ${DB_EXTERNAL_PORT}:27017
    env_file:
      - .env
    volumes:
      - alli_db_data:/data/db
      - alli_db_config:/data/configdb

  alli_backend:
    container_name: alli_backend
    image: alli_backend:${ENV_NAME}
    build:
      context: backend
      args:
        ENV_NAME: ${ENV_NAME}
    ports:
      - ${BACKEND_EXTERNAL_PORT}:8000
    env_file:
      - .env
    command: ${BACKEND_CMD}
    volumes:
      - ./backend/:/app/
    depends_on:
      - alli_db

  alli_frontend:
    container_name: alli_frontend
    image: node:16-alpine
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:3000
    command: npm run dev -- --host 0.0.0.0 --port 3000
    volumes:
      - ./frontend/:/app/
    working_dir: /app/

volumes:
  alli_db_data:
    driver: local
  alli_db_config:
    driver: local
