version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - 0.0.0.0:27017:27017
    # environment:
    #   MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
