version: "3.8"

services:
  alli_backend:
    container_name: alli_backend
    image: alli_backend:${ENV_NAME}
    ports:
      - ${BACKEND_EXTERNAL_PORT}:8000
    env_file:
      - .env.backend

  alli_frontend:
    container_name: alli_frontend
    image: alli_frontend:${ENV_NAME}
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:80


volumes:
  alli_db_data:
    driver: local
  alli_db_config:
    driver: local
